-- Script para aplicar la migración sin PostGIS temporalmente

-- Crear tabla de historial de migraciones si no existe
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- Crear tablas básicas sin tipos geometry
CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" character varying(20) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Trackers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "DeviceId" character varying(100) NOT NULL,
    "Model" character varying(50) NOT NULL,
    "BatteryLevel" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "LastSeen" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Trackers" PRIMARY KEY ("Id")
);

-- Agregar columnas de coordenadas a la tabla Farms si no existen
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Farms' AND column_name = 'Latitude') THEN
        ALTER TABLE "Farms" ADD COLUMN "Latitude" double precision NOT NULL DEFAULT 0;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Farms' AND column_name = 'Longitude') THEN
        ALTER TABLE "Farms" ADD COLUMN "Longitude" double precision NOT NULL DEFAULT 0;
    END IF;
END $$;

-- Registrar la migración
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250929143817_InitialCreateTables', '8.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;
